language: android
jdk: oraclejdk8

android:
  components:
    - build-tools-25.0.1

before_script:
  # Create and start emulator
  - emulator -avd Android7
  - ./wait_for_emulator

script: mvn install -Denv.USER=ANDROID
